language: java

os:
  - linux
jdk:
  - oraclejdk9
addons:
  apt:
    packages:
    - junit4
script:
  - make clean
  - make all
  - make runCov
  - make calCov

after_success:
  - bash <(curl -s https://codecov.io/bash)
